name: terraform-docs

on:
  pull_request:
    branches: [main]
    paths:
      - 'aws/**'
      - '.github/workflows/tf-docs.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    name: Generate terraform-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Render terraform docs and push changes back to PR
        uses: terraform-docs/gh-actions@v1
        with:
          working-dir: .
          recursive: true
          recursive-path: aws
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: 'docs(terraform-docs): auto-update README inputs/outputs tables'
          config-file: .terraform-docs.yml
          fail-on-diff: false
